.TH Golang Docker image
.PP
This repository contains the source for building various versions of
the Node.JS application as a reproducible Docker image.
Users can choose between RHEL and CentOS based builder images.
The resulting image can be run using Docker
\[la]http://docker.io\[ra]\&.

.SH Usage
.PP
TBD
